template: |
  ## What’s Changed

  $CHANGES
categories:
  - title: '🚀 Features'
    labels:
      - 'feat'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bug'
  - title: '🧰 Maintenance'
    label: 'chore'